pipeline {

    agent any

    parameters {
            string(name: 'APIGEE_ORG_P', defaultValue: 'apigeex-devops')
            string(name: 'APIGEE_ENV_P', defaultValue: 'eval')
            string(name: 'TEST_HOST_P', defaultValue: 'api.exco.com')
            string(name: 'WORK_DIR_P', defaultValue: 'Chapter08/crypto-aes-js')
            choice(name: 'GCP_SA_AUTH_P', choices: [ "jenkins-scope", "token" ], description: 'GCP SA/Token Scope'  )

            string(name: 'APIGEE_TOKEN_P', defaultValue: '')

            string(name: 'GIT_BRANCH_P', defaultValue: 'main')
            string(name: 'AUTHOR_EMAIL_P', defaultValue: 'cicd@exco.com')

    }

    environment {
        APIGEE_CREDS = credentials('apigee')
    }


    stages {
        stage('Version Check') {
            steps {
                sh "npm -v"
                sh "mvn -v"
        }}

        stage('Set Apigee Parameters') {
          steps {
            script{

              // env var/param precedence
              if( ! env.API_VERSION ){ env.API_VERSION = params.API_VERSION_P }
              if( ! env.APIGEE_ORG ){ env.APIGEE_ORG = params.APIGEE_ORG_P }
              if( ! env.APIGEE_ENV ){ env.APIGEE_ENV = params.APIGEE_ENV_P }
              if( ! env.TEST_HOST ){ env.TEST_HOST = params.TEST_HOST_P }
              if( ! env.WORK_DIR ){ env.WORK_DIR = params.WORK_DIR_P }
              if( ! env.GCP_SA_AUTH ){ env.GCP_SA_AUTH = params.GCP_SA_AUTH_P }

              if( ! env.APIGEE_TOKEN ){ env.APIGEE_TOKEN = params.APIGEE_TOKEN_P }

              if( ! env.GIT_BRANCH ){ env.GIT_BRANCH = params.GIT_BRANCH_P }
              if( ! env.AUTHOR_EMAIL ){ env.AUTHOR_EMAIL = params.AUTHOR_EMAIL_P }

              println "---------- Branch-Dependent Build Config ----------"
              println "Apigee Org: " + env.APIGEE_ORG
              println "Apigee Env: " + env.APIGEE_ENV
              println "Apigee Authentication Schema: " + env.GCP_SA_AUTH
            }
          }
        }

        stage('Install dependencies') {
          steps { dir( "${env.WORK_DIR}" ) {

              sh "npm install --silent --no-fund"
          } }
        }

        stage('Static Code Analysis') {
          steps { dir( "${env.WORK_DIR}" ) {
            sh "npm run eslint"

            sh "npm run apigeelint > apigeelint-out.html"

            publishHTML(target: [
              allowMissing: false,
              alwaysLinkToLastBuild: false,
              keepAll: false,
              reportDir: ".",
              reportFiles: 'apigeelint-out.html',
              reportName: 'Apigeelint Report'
            ]);
          }}
        }

        stage('Unit Test') {
          steps { dir( "${env.WORK_DIR}" ) {

            sh "npm run unit-test -- --ci --reporters=default --reporters=jest-junit"

          } }
        }

        stage('Commit Author Extraction') {
          steps {
            script {
              if (!env.AUTHOR_EMAIL) {
                env.AUTHOR_EMAIL = sh (
                  script: 'git --no-pager show -s --format=\'%ae\'',
                  returnStdout: true
                ).trim()
              }
            }
          }
        }

        stage('Deploy X/hybrid') {
            steps { dir( "${env.WORK_DIR}" ) {

           // Token precedence: env var; jenkins-scope sa; vm-scope sa; token;

            script {
              if (env.GCP_SA_AUTH == "jenkins-scope") {
                 withCredentials([file(credentialsId: 'apigee', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                   env.SA_TOKEN=sh(script:'oauth2l fetch --scope cloud-platform', returnStdout: true).trim()
                 }
              } else if (env.GCP_SA_AUTH == "token") {
                 env.SA_TOKEN=env.APIGEE_TOKEN
              }

             wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[password: env.SA_TOKEN, var: 'SA_TOKEN']]]) {
               sh """
                 mvn clean install \
                   -Pgoogleapi \
                   -Denv="${env.APIGEE_ENV}" \
                   -Dtoken="${env.SA_TOKEN}" \
                   -Dorg="${env.APIGEE_ORG}" \
                   -Ddeployment.description="Jenkins Build: ${env.BUILD_TAG} Author: ${env.AUTHOR_EMAIL}"
                """
              }
            }
          } }
        }

        stage('Functional Test') {
          steps { dir( "${env.WORK_DIR}" ) {
            sh "TEST_HOST=${env.TEST_HOST} node ./node_modules/.bin/cucumber-js ./target/test/integration --format json:./target/reports.json"
          } }
        }
    }

    post {
      always { dir( "${env.WORK_DIR}" ) {
        recordIssues  enabledForFailure: true, 
            aggregatingResults: true,
            tools: [checkStyle(pattern: 'eslint-report.xml')]

        junit 'junit.xml'

        cucumber reportTitle: 'Apickli test report',
            fileIncludePattern: '**/reports.json',
            jsonReportDirectory: "target",
            sortingMethod: 'ALPHABETICAL',
            trendsLimit: 10
        } }
    }
}