
services:
  apigee-kickstart:
    image: ghcr.io/apigee/docker-apigee-drupal-kickstart:v1.0.1
    ports:
    - "8080:80"
    environment:
    - DRUPAL_DATABASE_NAME=apigee_devportal
    - DRUPAL_DATABASE_USER=dbuser
    - DRUPAL_DATABASE_PASSWORD=passw0rd
    - DRUPAL_DATABASE_HOST=apigee-kickstart-database
    - DRUPAL_DATABASE_PORT=3306
    - DRUPAL_DATABASE_DRIVER=mysql
    - AUTO_INSTALL_PORTAL=${AUTO_INSTALL_PORTAL}
    links:
    - apigee-kickstart-database
    depends_on:
      apigee-kickstart-database:
        condition: service_healthy
    volumes:
    - drupal-sites-default-volume:/app/code/web/sites/default
  apigee-kickstart-database:
    image: mariadb:11.4.2
    volumes:
    - apigee-kickstart-database-volume:/var/lib/mysql:delegated
    environment:
    - MYSQL_DATABASE=apigee_devportal
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=passw0rd
    - MYSQL_ROOT_PASSWORD=rootpasswd
    healthcheck:
      test: [ "CMD-SHELL", 'mariadb --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="show tables;" --skip-column-names -B' ]
      interval: 10s
      timeout: 10s
      retries: 6
volumes:
  apigee-kickstart-database-volume:
  drupal-sites-default-volume:
